language: node_js

node_js:
 - "6"

after_success:
 - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
 - bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/travis/scripts/upload)
